# Generated by Django 4.1.5 on 2023-01-21 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_alter_userbooksrelation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='readers',
            field=models.ManyToManyField(related_name='readers', through='store.UserBooksRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='books',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
